# Generated by Django 5.0.6 on 2026-06-09 20:17

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requisitos', '0001_initial'),
        ('stakeholders', '0002_alter_stakeholder_observacoes_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TemplateElicitacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('descricao', models.TextField(blank=True, verbose_name='Descricao')),
            ],
            options={
                'verbose_name': 'Template de Elicitacao',
                'verbose_name_plural': 'Templates de Elicitacao',
            },
        ),
        migrations.AddField(
            model_name='requisito',
            name='projeto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requisitos', to='stakeholders.projeto'),
        ),
        migrations.AlterField(
            model_name='requisito',
            name='codigo',
            field=models.CharField(max_length=10, unique=True, verbose_name='Codigo'),
        ),
        migrations.AlterField(
            model_name='requisito',
            name='descricao',
            field=models.TextField(verbose_name='Descricao'),
        ),
        migrations.AlterField(
            model_name='requisito',
            name='prioridade',
            field=models.CharField(choices=[('alta', 'Alta'), ('media', 'Media'), ('baixa', 'Baixa')], default='media', max_length=10, verbose_name='Prioridade'),
        ),
        migrations.AlterField(
            model_name='requisito',
            name='status',
            field=models.CharField(choices=[('rascunho', 'Rascunho'), ('em_revisao', 'Em Revisao'), ('aprovado', 'Aprovado'), ('rejeitado', 'Rejeitado')], default='rascunho', max_length=15, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='requisito',
            name='tipo',
            field=models.CharField(choices=[('funcional', 'Funcional'), ('nao_funcional', 'Nao Funcional')], default='funcional', max_length=15, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='requisito',
            name='titulo',
            field=models.CharField(max_length=200, verbose_name='Titulo'),
        ),
        migrations.CreateModel(
            name='HistoricalRequisito',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('codigo', models.CharField(db_index=True, max_length=10, verbose_name='Codigo')),
                ('titulo', models.CharField(max_length=200, verbose_name='Titulo')),
                ('descricao', models.TextField(verbose_name='Descricao')),
                ('tipo', models.CharField(choices=[('funcional', 'Funcional'), ('nao_funcional', 'Nao Funcional')], default='funcional', max_length=15, verbose_name='Tipo')),
                ('prioridade', models.CharField(choices=[('alta', 'Alta'), ('media', 'Media'), ('baixa', 'Baixa')], default='media', max_length=10, verbose_name='Prioridade')),
                ('status', models.CharField(choices=[('rascunho', 'Rascunho'), ('em_revisao', 'Em Revisao'), ('aprovado', 'Aprovado'), ('rejeitado', 'Rejeitado')], default='rascunho', max_length=15, verbose_name='Status')),
                ('criado_em', models.DateTimeField(blank=True, editable=False)),
                ('atualizado_em', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('criado_por', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('projeto', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='stakeholders.projeto')),
            ],
            options={
                'verbose_name': 'historical Requisito',
                'verbose_name_plural': 'historical Requisitos',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='MensagemChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensagem', models.TextField(verbose_name='Mensagem')),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('likes', models.ManyToManyField(blank=True, related_name='likes_mensagens', to=settings.AUTH_USER_MODEL)),
                ('requisito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensagens', to='requisitos.requisito')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mensagem do Chat',
                'verbose_name_plural': 'Mensagens do Chat',
                'ordering': ['data'],
            },
        ),
        migrations.CreateModel(
            name='PerguntaTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField(verbose_name='Pergunta')),
                ('ordem', models.IntegerField(default=0, verbose_name='Ordem')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='perguntas', to='requisitos.templateelicitacao')),
            ],
            options={
                'ordering': ['ordem'],
            },
        ),
    ]
