# Generated by Django 5.0.6 on 2026-06-08 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stakeholder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, verbose_name='Nome')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='E-mail')),
                ('papel', models.CharField(choices=[('cliente', 'Cliente Solicitante'), ('analista', 'Analista de Requisitos'), ('dev', 'Equipe Dev/QA'), ('pmo', 'Gerente de Projetos / PMO'), ('suporte', 'Suporte / Manutenção'), ('compliance', 'Compliance / Jurídico'), ('outro', 'Outro')], max_length=20, verbose_name='Papel')),
                ('contato', models.CharField(blank=True, max_length=50, verbose_name='Contato / Telefone')),
                ('responsabilidade', models.CharField(choices=[('alta', 'Alta'), ('media', 'Média'), ('baixa', 'Baixa')], default='media', max_length=10, verbose_name='Nível de Responsabilidade')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Stakeholder',
                'verbose_name_plural': 'Stakeholders',
                'ordering': ['nome'],
            },
        ),
    ]
