# Generated by Django 5.0.6 on 2026-06-09 20:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stakeholders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='stakeholder',
            name='observacoes',
            field=models.TextField(blank=True, verbose_name='Observacoes'),
        ),
        migrations.AlterField(
            model_name='stakeholder',
            name='papel',
            field=models.CharField(choices=[('cliente', 'Cliente Solicitante'), ('analista', 'Analista de Requisitos'), ('dev', 'Equipe Dev/QA'), ('pmo', 'Gerente de Projetos / PMO'), ('suporte', 'Suporte / Manutencao'), ('compliance', 'Compliance / Juridico'), ('outro', 'Outro')], max_length=20, verbose_name='Papel'),
        ),
        migrations.AlterField(
            model_name='stakeholder',
            name='responsabilidade',
            field=models.CharField(choices=[('alta', 'Alta'), ('media', 'Media'), ('baixa', 'Baixa')], default='media', max_length=10, verbose_name='Nivel de Responsabilidade'),
        ),
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome')),
                ('descricao', models.TextField(blank=True, verbose_name='Descricao')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('dono', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projetos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Projeto',
                'verbose_name_plural': 'Projetos',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.AddField(
            model_name='stakeholder',
            name='projeto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stakeholders', to='stakeholders.projeto'),
        ),
    ]
